version: '3.3'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    environment:
      VIRTUAL_HOST: "portainer.${DOMAIN?Variable not set}"
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: "portainer.${DOMAIN?Variable not set}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    networks:
      web_proxy:
      default:

networks:
  web_proxy:
    external: true

volumes:
  data:
