version: '3.3'

services:
  server:
    image: influxdb:2.2-alpine
    restart: always
    environment:
      VIRTUAL_HOST: "influxdb.${DOMAIN?Variable not set}"
      VIRTUAL_PORT: 8086
      LETSENCRYPT_HOST: "influxdb.${DOMAIN?Variable not set}"
    volumes:
      - data:/var/lib/influxdb2
    networks:
      web_proxy:
      default:

networks:
  web_proxy:
    external: true

volumes:
  data:
